### ISSUE TITLE
주제 선정하기

### ISSUE THREAD

**Issue by JesungKoo** [SKKUCS/graduationProject#1]
AI 확정

어떤 Approach? CNN? RNN? GAN? 아니면 러닝?

**Comment by WinteringAsch** [comment]
주제를 바꾼다면
    1. SC2를 다른 게임으로
    2. AI 구현체에서 NLP로
    3. SC2는 그대로, 범위를 다르게

**Comment by WinteringAsch** [comment]
주제에 관해서 의견 있으면 바로 공유해주렴...
나는 아직까진 슈퍼마리오 + @ 말고는 더 떠오르는게 없다.
