### ISSUE TITLE
gym 이해

### ISSUE THREAD

**Issue by JesungKoo** [SKKUCS/graduationProject#13]
gym 아키텍쳐 분석 시도해봅니당..

**Comment by WinteringAsch** [comment]
https://keon.io/deep-q-learning/
https://medium.com/coinmonks/build-your-first-ai-game-bot-using-openai-gym-keras-tensorflow-in-python-50a4d4296687

**Comment by WinteringAsch** [comment]
다시 코드를 짜보는 중... 이번엔 텐서플로가 아닌 케라스 이용해서 짜볼듯 하다. 차이점은 추후 기재 예정

**Comment by WinteringAsch** [comment]
음, 현재까지 이해한바로는 케라스가 좀더 코드를 직관적으로 짤수 있을 것으로 기대됨.
그냥 예제의 차이일 뿐, 텐서플로를 이용해서도 똑같은 방식으로도 짤 수는 있겠지만... 기능별로 클래스를 따로 지정하는건 아직까진 케라스를 통해서 하는게 더 익숙할 것 같다.
그리고, 더 코드를 짜기 전에, 우리가 구현할 신경망, 사용하는 수식 등을 한번 문서화시켜두는것이 좋겠다는 생각을 함.

**Comment by WinteringAsch** [comment]
순서의 차이가 있긴 하지만, 결국 랜덤 액션으로 시작-> 데이터 만들기 -> 학습하기 -> 학습된 데이터로 플레이의 큰 틀을 가진다.

**Comment by WinteringAsch** [comment]
다른 학습 이슈와 중복된 것으로 판단해 닫음
