### ISSUE TITLE
제안서 제출하기

### ISSUE THREAD

**Issue by JesungKoo** [SKKUCS/graduationProject#3]
1. 과제 필요성 3p
2. 선행연구 및 기술현황 2p
3. 작품/논문 전체 진행계획 및 구성 2p
4. 기대효과 및 개선방향 1p
5. 기타 1p
6. 참고문헌 1p

**Comment by JesungKoo** [comment]
기타는 역할 분담 및 실행 계획임. 
기타, 참고문헌, 작품/논문 전체 진행계획 및 구성은 같이 할 수 밖에 없기 때문에 분담해야 할 양은 과제필요성과 선행 연구 및 기술/ 기대효과 및 개선

**Comment by WinteringAsch** [comment]
[제안서관련서식.zip](https://github.com/SKKUCS/graduationProject/files/2387201/default.zip)

**Comment by JesungKoo** [comment]
깃헙 내에서 쉽게 읽고 공유하기 위해 마크다운 형식으로 레포지토리에 추가함

**Comment by JesungKoo** [comment]
[양식.zip](https://github.com/SKKUCS/graduationProject/files/2388743/default.zip)

docx 파일 만들어 담아봤는데 되는지 확인 요망 @WinteringAsch

**Comment by WinteringAsch** [comment]
[book.pdf](https://github.com/SKKUCS/graduationProject/files/2392233/book.pdf)
game ai 관련 자료...
양식 docx는 좀 형식이 깨진것 같아 다른 방법 필요한 것으로 보임 @silvermist152

**Comment by WinteringAsch** [comment]
https://youtu.be/exXD6wJLJ6s
강화학습과 딥러닝을 이용한 쿠키런 ai

**Comment by JesungKoo** [comment]
전체 기간: 2018-09-21 ~ 2019-05-01

9월: 자료조사, 방법론 연구 (말까지 어떤 게임할 지 정함)
10월: 세부 주제 확정, 사용 기술 확정. - 관련 문서 및 데이터 수집
11월: 기술 학습
12월: 기획안 및 스토리보드 작성
1월: 구현 작업
2월: 구현 작업
3월: 구현 최종 및 디버깅
4월: 시뮬레이션 및 러닝

**Comment by WinteringAsch** [comment]
[proposal.zip](https://github.com/SKKUCS/graduationProject/files/2400060/proposal.zip)

**Comment by JesungKoo** [comment]
제안서 제출 완료
